[NbClientApp] WARNING | Config option `kernel_spec_manager_class` not recognized by `NbClientApp`.
[NbClientApp] Executing Testing.ipynb
[NbClientApp] Executing notebook with kernel: python3
wandb: Waiting for W&B process to finish... (success).
wandb: - 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)Traceback (most recent call last):
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/bin/jupyter-execute", line 10, in <module>
    sys.exit(main())
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/traitlets/config/application.py", line 975, in launch_instance
    app.initialize(argv)
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/nbclient/cli.py", line 113, in initialize
    [self.run_notebook(path) for path in self.notebooks]
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/nbclient/cli.py", line 113, in <listcomp>
    [self.run_notebook(path) for path in self.notebooks]
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/nbclient/cli.py", line 154, in run_notebook
    client.execute()
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/nbclient/client.py", line 707, in async_execute
    await self.async_execute_cell(
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/nbclient/client.py", line 1025, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/gs/gsfs0/hpc01/rhel8/apps/conda3/lib/python3.9/site-packages/nbclient/client.py", line 919, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for SPARSITY in [0.2, 0.4, 0.6, 0.8, 1]:
    loaded_model = OPTForCausalLM.from_pretrained(f'facebook/{model_name}', output_attentions=True, output_hidden_states=True).to(device=device) # type: ignore
    
    if SPARSITY != 1:
        load_into_model(loaded_model, f'pruned_models/{model_name}-{SPARSITY}.pt')
    loaded_model = torch.nn.DataParallel(loaded_model, device_ids=[0,1,2,3])
    loaded_model.eval()
    perp_sparse = 0
    for batch_idx, (input_ids, attention_mask) in enumerate(loop):
        batch_dict = {'input_ids': input_ids,'attention_mask':attention_mask}
        with torch.no_grad():
            sparse_output = loaded_model(**batch_dict, labels=batch_dict['input_ids'])
            perp_sparse += torch.exp(sparse_output.loss)
    perp_sparse /= len(wikiset)
    wandb.log({"sparse_perplexity": perp_sparse, 'sparsity': SPARSITY})
    del loaded_model
    gc.collect()
    torch.cuda.empty_cache()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 1>[0;34m()[0m
[1;32m     11[0m     [38;5;28;01mwith[39;00m torch[38;5;241m.[39mno_grad():
[1;32m     12[0m         sparse_output [38;5;241m=[39m loaded_model([38;5;241m*[39m[38;5;241m*[39mbatch_dict, labels[38;5;241m=[39mbatch_dict[[38;5;124m'[39m[38;5;124minput_ids[39m[38;5;124m'[39m])
[0;32m---> 13[0m         perp_sparse [38;5;241m+[39m[38;5;241m=[39m torch[38;5;241m.[39mexp(sparse_output[38;5;241m.[39mloss)
[1;32m     14[0m perp_sparse [38;5;241m/[39m[38;5;241m=[39m [38;5;28mlen[39m(wikiset)
[1;32m     15[0m wandb[38;5;241m.[39mlog({[38;5;124m"[39m[38;5;124msparse_perplexity[39m[38;5;124m"[39m: perp_sparse, [38;5;124m'[39m[38;5;124msparsity[39m[38;5;124m'[39m: SPARSITY})

[0;31mRuntimeError[0m: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0
RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0

